app:
  name: "wizzCommunity"
  mode: "dev"
  port: 8083
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 112.126.78.122
  port: 3306
  user: "root"
  password: "admin"
  dbname: "wizzcommunity"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 112.126.78.122
  port: 6379
  password: ""
  db: 0
  pool_size: 100